development:
  adapter: enhanced_postgresql

test:
  adapter: test

production:
  adapter: enhanced_postgresql
  # adapter: redis
  # url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  # channel_prefix: buzzer_production
